### PR TITLE
SELF BOTS ARE BAD!

### PR DESCRIPTION
**Pull request by SilverCory**
DO NOT USE SELF BOTS
SELF BOTS ARE BAD.

DISCORDS API IS SENSITIVE AND WILL GO DOWN IF YOU USE A SELF BOT.

### CODE REVIEW

**Comment by Rhodesia** [comment]
all memeing aside, this is ironic as hell that you report Cory for selfbotting and yet you have your own selfbot. You should be ashamed of yourself

**Comment by SilverCory** [comment]
@Rhodesia SELF BOTS ARE AGAINST THE DISCORD ToS, YOU AGREEED TO THE DEVELOPER DOCUMENTATION WHEN YOU AGREED TO THE ToS EVEN THOUGH THERE WAS NO MENTION OF THIS.

**Comment by Proximyst** [comment]
@Rhodesia > Last commit: May 14
Uh?

@SilverCory > Not a serious PR, and will not be merged. //Closed.

**Comment by SilverCory** [comment]
Last commit is of no importance!

**Pull request closed without merging**
